development:
  adapter: postgresql
  encoding: unicode
  database: RubyWC_development
  host: localhost
  pool: 2
  username: longlong
  password: a5879632

production:
  adapter: postgresql
  encoding: unicode
  database: RubyWC_production
  pool: 2
  host: localhost
  username: longlong
  password: a5879632
